services:
  spark-master:
    image: velnae28/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ./src:/src  # Volumen para scripts Python
    networks:
      - default
  spark-worker-1:
    image: velnae28/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - default

networks:
  default:
    name: docker-hadoop
    external: true